### ISSUE TITLE
After docker restart node4j information is gone

### ISSUE THREAD

**Issue by VlaD-T** [softvis-research/Getaviz#105]
Am not sure if this is a bug or not. After we restart the docker (with docker-compose down/up) all the information (nodes, labels) is gone. Is it possible to leave it there? 

Use case: currently, if I restart the docker and open the browser, I see the model I've generated last. If we rebuild it to get the data from Neo4j, then there'll be no model to show.

**Comment by naraesk** [comment]
The data is inside the container. If you delete the container, you delete the data.

There is a difference between stopping the container (docker-compose stop or Ctrl + C) and destroying the container (docker-compose down). In most cases stopping the container will be enough, than the data should not be deleted.

In future we can add a volume to the docker-compose.yml to make sure the data survives a docker-compose stop.

**Comment by naraesk** [comment]
fixed on development
