### ISSUE TITLE
Where are AframeCanvasManipulator methods called from?

### ISSUE THREAD

**Issue by VlaD-T** [softvis-research/Getaviz#107]
Cannot understand, where this controller is called or what it is called by. 
I'm activating/hiding elements in PackageExplorer and see errors, which are coming from AframeCanvasManipulator Controller. In PackageExplorer I see no methods from this another controller. 

Currently I'm loading the elements from Neo4j and afterwards create the a-frame element on the page, so I need to run this AframeCanvasManipulator after the elements were created.

**Comment by naraesk** [comment]
The functions are not called directly, but triggered by events: 
https://github.com/softvis-research/Getaviz/wiki/Architecture-UI#actions-and-events
