### ISSUE TITLE
RelationTransparencyController bad fix

### ISSUE THREAD

**Issue by VlaD-T** [softvis-research/Getaviz#109]
Found a place in RelationTransparencyController  with a "bad fix" where stays 
> realy realy bad fix for one model where elements in scene but not in model...

What is it for model? I can't think of any.

![grafik](https://user-images.githubusercontent.com/14137015/66635264-1dcab800-ec0f-11e9-8b03-4f6dc89c8898.png)

**Comment by naraesk** [comment]
Guess @PascalKovacs knows more about this.

I'd assume, if we create connections (the red lines between elements) in the RelationConnectorController we have elements, that are part of the scene but not of our model.
