### ISSUE TITLE
Neo4j - get all direct child nodes

### ISSUE THREAD

**Issue by VlaD-T** [softvis-research/Getaviz#122]
Hello, 
Is there some nice way to find out if node has child nodes and get them using hash of parent? 
The only option I have is to make cypher query, like: 

`
"MATCH (node)-[:CONTAINS|DECLARES]->(child) WHERE node.hash = "***" RETURN child.hash";
`

Thanks in advance!

**Comment by naraesk** [comment]
You can use `EXISTS()`:
https://stackoverflow.com/questions/42022215/test-if-relationship-exists-in-neo4j-spring-data/42022583

**Comment by VlaD-T** [comment]
Thanks for the reply! 

```MATCH (parent)-[:DECLARES|HAS|CONTAINS]->(child) WHERE parent.hash = "ID_736ff4e8c509af97b93144e21132e8b6f9810a26" RETURN child```

This query gives me all direct child nodes of given parent node. Can't really understand how to rewrite it with ```EXISTS()``` function.

**Comment by naraesk** [comment]
MATCH (parent)-[:DECLARES|HAS|CONTAINS]->(child) 
WHERE parent.hash = "ID_736ff4e8c509af97b93144e21132e8b6f9810a26" AND EXISTS(child.hash) RETURN child

**Comment by VlaD-T** [comment]
Thanks!
