### ISSUE TITLE
a-register-element.js  - deprecated code

### ISSUE THREAD

**Issue by VlaD-T** [softvis-research/Getaviz#124]
Hi, 
noticed that Chrome is giving a warning message in console about A-Frame "Register-Element" component.

> Deprecation] **document.registerElement is deprecated** and will be removed in M80, around February 2020. Please use window.customElements.define instead. See https://www.chromestatus.com/features/4642138092470272 and https://developers.google.com/web/updates/2019/07/web-components-time-to-upgrade for more details.

a-register-element.js
![grafik](https://user-images.githubusercontent.com/14137015/69234896-8b63ef80-0b90-11ea-9958-bf2ccb8d38cf.png)

**Comment by naraesk** [comment]
this is aframe code, not our code
