### ISSUE TITLE
AFRAME is not defined

### ISSUE THREAD

**Issue by VlaD-T** [softvis-research/Getaviz#128]
Interesting behaviour in Google Chrome: after creating a new visualization the model is not loading. 
Seeing this for the first time. In firefox everything works fine. Crome was reloaded several times, but it doesn't help. 🤔 

![grafik](https://user-images.githubusercontent.com/14137015/71187445-65a93380-227f-11ea-8095-30cdf1683712.png)

Aframe is also loaded, so can't really understand what is missing.. 
![grafik](https://user-images.githubusercontent.com/14137015/71188095-9c337e00-2280-11ea-8306-ddc6719e1da6.png)

**Comment by naraesk** [comment]
Noticed the same today. Without any change to the code and all our A-Frame dependencies are static/offline. But this week chrome got a mayor update on all platforms: https://chromereleases.googleblog.com/ so most likely this is a chrome bug. Seems like chrome loads the JavaScript files in the wrong order or something like that.

**Comment by naraesk** [comment]
Upgrading A-Frame to 1.0.0 seems to fix this.
- Update package.json
- run `npm install` in ui directory
- Update index.php (replace 0.9.1 with 1.0.0)

**Comment by VlaD-T** [comment]
Thank you. This fixed the problem.
