### ISSUE TITLE
Usage page - update info

### ISSUE THREAD

**Issue by VlaD-T** [softvis-research/Getaviz#130]
Followinf link, under "**Generating a visualization manually**" must be updated:
_http://central.maven.org/maven2/com/android/tools/build/gradle/0.1/gradle-0.1.jar_ 

to:
_https://repo1.maven.org/maven2/com/android/tools/build/gradle/0.1/gradle-0.1.jar_

**Comment by naraesk** [comment]
Thanks, fixed. Have to check if you use this for some test cases.
