### ISSUE TITLE
Generate visualization from local .jar file

### ISSUE THREAD

**Issue by Lyannen258** [softvis-research/Getaviz#147]
Is it possible to generate a visualization from a local .jar file without hosting it?

I already tried mounting a volume to /var/lib/jetty/analyze and adding the .jar file in that directory. In the User Interface I then tried to provide an absolute path or file url (file://var/lib...) for input.files but that did not work due to the method ClassLoader.getResource returning null in SettingsConfiguration.getInputFiles().

**Comment by naraesk** [comment]
Your approach sounds right, actually. I'll check it out.

**Comment by naraesk** [comment]
This should work now on development branch. I've updated the manual: https://github.com/softvis-research/Getaviz/wiki/Usage. Just a workaround but should work for now. Have a GUI for this would be better, of course.

**Comment by Lyannen258** [comment]
Thanks for the fix. This is exactly what I was looking for. I just think you haven't pushed your changes to the repository yet. The latest commit I see on the development branch is from march.

**Comment by naraesk** [comment]
fixed (:
