### ISSUE TITLE
Debug the backend container

### ISSUE THREAD

**Issue by Lyannen258** [softvis-research/Getaviz#148]
Is it possible to debug the backend container?

According to the [jetty docs](https://www.eclipse.org/jetty/documentation/9.4.28.v20200408/enable-remote-debugging.html) it is possible to debug applications deployed to jetty by adding the jwdp debug parameters (-Xdebug -agentlib:jdwp=transport=dt_socket,address=9999,server=y,suspend=n) to the jvm. I tried to add those parameters by adding them as environment variables in the docker-compose.yml as seen below. The container indeed outputs "Listening for transport dt_socket at address: 9999" but is then exiting with code 127 because of an error in docker-entrypoint.sh and keeps restarting.

![grafik](https://user-images.githubusercontent.com/39589794/81814369-fb907400-9528-11ea-9166-462c88a2af86.png)
![grafik](https://user-images.githubusercontent.com/39589794/81814573-3beff200-9529-11ea-9d64-17c47ea1975c.png)

Am I doing something wrong or is there another way to troubleshoot while developing?

**Comment by naraesk** [comment]
I've never tried this to be honest. The easiest way to debug is running the unit tests in debug mode.

**Comment by Lyannen258** [comment]
That was also my first approach and it worked very well until I tried to run the scan jar test. I configured it by downloading jqassistant and providing the path to the executable. While executing the test, jqassistant threw a SecurityException as it tried to connect to the neo4j database which resulted in the test failing. I tried to run the jqassistant command manually with different databases but the problem still existed. That is probably an issue with jqassistant i have to look into. I just tried to get around that by using the container.

**Comment by naraesk** [comment]
Can you share the jar file?

**Comment by Lyannen258** [comment]
The jar file is the default one provided with the test org.getaviz.generator.extract.ScanJarTest.
![grafik](https://user-images.githubusercontent.com/39589794/81960929-fb1fd800-9611-11ea-8583-abda430f480a.png)

When I am executing the test it won't get past this point:
![grafik](https://user-images.githubusercontent.com/39589794/81961830-37076d00-9613-11ea-94f3-cc957313d9d9.png)

Which is because the process started here is not terminating:
![grafik](https://user-images.githubusercontent.com/39589794/81962310-d62c6480-9613-11ea-80d8-c349e4a0c099.png)

I tried to run the exact same command manually while having a neo4j database set up and listening on the given port, which results in the following:
![grafik](https://user-images.githubusercontent.com/39589794/81963591-949cb900-9615-11ea-809d-91c552c9d019.png)

That's why I'm thinking that it is an issue with jqassistant or Windows 10.

**Comment by naraesk** [comment]
Not sure, what's the problem here. Let's stick with ScanJarTest. Which version of jQAssistant and jdk/java are you using? The test starts a database so make sure the port is not blocked from another instance or so!

Also, how did you start the database? Maybe adding encrypted=false is required
https://stackoverflow.com/questions/60023381/securityerror-failed-to-establish-secure-connection-to-eof-occurred-in-violati

**Comment by Lyannen258** [comment]
jqassistant: 1.8.0
java: 1.8.0_251

I'm sure the port isn't bocked, because I was able to stop the test execution on a breakpoint and then access the database through the frontend.

I tested different ways to start the database. I executed the test and then stopped it at a breakpoint and used the embedded database. I was also running the official neo4j docker container. In both cases jqassistant wasn't able to connect.

I think the post on stackoverflow is going into the right direction. Probably jqassistant needs an encrypted database (maybe in some newer versions) and the one, that is embedded in the test, isn't encrypted. The problem is: It's not possible to add encrypted=false to jqassistant.

**Comment by naraesk** [comment]
Could you please try with jQAssistant 1.7?

**Comment by Lyannen258** [comment]
That did the trick. Apparently there is an issue with version 1.8. Thank you for your help.

If I find the time, I will open an issue on the jQAssistant repository.

**Comment by naraesk** [comment]
Thanks for testing, I will update the wiki accordingly. jQAssistant 1.8 comes with a newer neo4j version, so it might be our fault mixing incompatible versions.
