### ISSUE TITLE
C# extractor does not work without silently (i.e. without human interaction)

### ISSUE THREAD

**Issue by pvillads** [softvis-research/Getaviz#28]
The current C# extractor needs input from the user as to what directory to parse, and where to put the resulting file. It even ends with a Console.ReadLine(), stopping it until the user presses Enter. This makes it useless for CI/CD scenarios (where the tool is run in a nightly build for instance). Instead, make it into a real command line tool, possibly with https://github.com/commandlineparser/commandline (which is the one I happen to prefer, with a permissive MIT license). Then:

generateCsharp myDll.dll >myresult.famix

You would then write error messages to stderr and the result would be spit out to standard out, so that it can take part in other tools in the pipeline.

**Comment by naraesk** [comment]
Deprecated, since we no longer use famix as input source. Once there is a C# or .NET plugin for jQAssistant available, we will support it again.
