### ISSUE TITLE
C# extractor confuses parameter and statement counts?

### ISSUE THREAD

**Issue by pvillads** [softvis-research/Getaviz#29]
By chance I stumbled over this:
            sb.Append("\t\t(numberOfStatements " + Parameters.Count + ")");
in Method.cs.

To me this looks wrong.

**Comment by naraesk** [comment]
The C# extractor is very rudimentary compared to the Java or Ruby extractor. I'm not the original author, but as far as I know it was not possible retrieve number of statement or lines of code from the  dll/exe files. Number of paremets was chosen as a substitute metric for method size/complexity.

It would be more straight forward to write a jQAssistant plugin for managed code rather than extend the current C# extractor.

**Comment by pvillads** [comment]
I do not know about jQAssistant, since my background is in the managed world, not in Java.

There are several problems with the approach that is used in the current extractor for C#

  1.  It works at the assembly level. This means that methods that the compiler generated for the user are part of the information surfaced in the model, and that is probably not what the user wants to see.
  2.  Again, because of the assembly level it is close to impossible to build derived information, like coupling of methods, lines of source code, or reason over comment lines etc.

Instead, I think if I were writing this from scratch, I would go with the Microsoft.Compiler namespace that allows you to build rich ASTs from any C# of VB.NET source code. It contains all the information from the source – nothing is thrown away. It is all open source, and it is what the commercial compiler Microsoft ships is built with. If you want to investigate, start here: https://github.com/dotnet/roslyn

BR PV

**Comment by naraesk** [comment]
I agree with you, Roslyn is probably the right way. However, doing this as a side project is beyond our capabilities as a (small) research group. Visualizing C# was just a feasibility study. From a scientific point of view, it is not so important if we visualize .NET or Java source code.

Technically, we can support any language. But in most cases we rely on contributions from the open source community or resources from industry partners to do the implementation.

**Comment by naraesk** [comment]
Deprecated, since we no longer use famix as input source. Once there is a C# or .NET plugin for jQAssistant available, we will support it again.
