### ISSUE TITLE
Error in docker

### ISSUE THREAD

**Issue by skyyangman** [softvis-research/Getaviz#68]
![Snipaste_2019-04-04_14-08-48](https://user-images.githubusercontent.com/37643371/55533471-f6d17d80-56e3-11e9-9de8-4ac1f889b553.jpg)

take a look at [here](https://unix.stackexchange.com/questions/508724/failed-to-fetch-jessie-backports-repository) might help.

**Comment by naraesk** [comment]
This is already fixed on development, see issue #65
