### ISSUE TITLE
Incorrect username or password (pulling db)

### ISSUE THREAD

**Issue by VlaD-T** [softvis-research/Getaviz#74]
![image](https://user-images.githubusercontent.com/14137015/58172444-f17ec100-7c98-11e9-906f-f5c90d9cfaf9.png)

Just started docker-compose up and received an error.

**Comment by naraesk** [comment]
Found many different threads for this message, please have a look at:
https://github.com/docker/for-mac/issues/2640
https://github.com/docker/hub-feedback/issues/1103

They suggest that you either have to delete an invalid auth token on your system and/or login via the docker cli and then everything should work. Not sure why you have to login for pulling an public image from docker hub, but it seems as this is not a problem of our setup.

**Comment by VlaD-T** [comment]
It works. Thanks.
