### ISSUE TITLE
Local development 

### ISSUE THREAD

**Issue by VlaD-T** [softvis-research/Getaviz#76]
I'm trying to make some changes to UI (Vizualisation form) and actually already did some changes in file, but in debugger is shown the old version. I'm working with "Getaviz -> ui" folder. Tried to restart docker (just to be sure) and check ui in another browser, but none of that worked. 
My question is - where should I change UI files and if it was the right place, what do I have to do, so that my changes appear? 

Thank you in advance!

**Comment by naraesk** [comment]
Some days ago I created the page [Local Development](./wiki/Local Development). Have you done the steps described there (especially step 3 to 5)? If everythings set up correctly you can change the files in the ui directory and they will be taken into account automatically.

**Comment by VlaD-T** [comment]
Hm.. first step - build the generator. (jdk and maven are installed)
![grafik](https://user-images.githubusercontent.com/14137015/58497921-40d35e80-817d-11e9-9a16-7ff9e74623ec.png)

**Comment by naraesk** [comment]
Hm, the path is calculated by java. I'll have a look at this. Anyway, for ui development you don't neet the generator. Just start wtih step 3. Guess it's a good idea to split the wiki into two sections.

**Comment by naraesk** [comment]
Improved the wiki and the comments in docker-compose.yml with commit 9f5074bab7ed836baa9c0d19c76a2179762fa7e1

**Comment by VlaD-T** [comment]
Hm.. after uncomennting this part:
![grafik](https://user-images.githubusercontent.com/14137015/58540862-82eeb580-81fa-11e9-8d8e-f04a08e47a7f.png)

Came to the following error: 
![grafik](https://user-images.githubusercontent.com/14137015/58540825-6d798b80-81fa-11e9-8f75-fb740b5b8e77.png)

**Comment by naraesk** [comment]
True, this only works if the generater has been build successfully. As long as this is not fixed, just leave this line as it is

**Comment by naraesk** [comment]
btw, as long as the test is not working on Windows you can execute `mvn install -DskipTests` to build the generator without running the tests

**Comment by naraesk** [comment]
Can you please test if test cases now work on Windows wtih the latest development commit?

**Comment by VlaD-T** [comment]
Actualized my local development branch and tried "docker-compose up".
Opened Getaviz Page and started new visualization. 

![grafik](https://user-images.githubusercontent.com/14137015/60188174-25687b80-982f-11e9-8230-c8d88b01e451.png)

![grafik](https://user-images.githubusercontent.com/14137015/60188234-40d38680-982f-11e9-85a8-0c5e21b612eb.png)


Should I try to run any build command or should it already be functioning? :/

**Comment by naraesk** [comment]
Hsa this anything to do with the original issue? :-)

Yes, you have to rebuild the container as described here: https://github.com/softvis-research/Getaviz/issues/84

**Comment by VlaD-T** [comment]
Wasn't sure :D ok, I suppose we can close this issue.
