### ISSUE TITLE
Cannot start service 

### ISSUE THREAD

**Issue by VlaD-T** [softvis-research/Getaviz#78]
![Screenshot_1](https://user-images.githubusercontent.com/14137015/58540399-96e5e780-81f9-11e9-8cb2-788d4738673d.png)

Problem: some ports are blocked. The problem is, that Windows 10 after shutdown actually doesn't close connections.

**Comment by VlaD-T** [comment]
Possible solution: (worked fine for me)
1) Disable autostart for docker;
2) In `cmd `execute `shutdown /s /t 0`;
3) After Windows is up again, start `resmon.exe`, just to be sure, that ports are free;
4) Run `docker-compose up`.

**Comment by naraesk** [comment]
Thanks for sharing your solution. Have you tried if the containers are running before invoking docker-compose up? When they are up and you reboot Windows, the containers will restart automatically.

**Comment by VlaD-T** [comment]
Possible solution: (worked fine for me)
1) Disable autostart for docker;
2) In `cmd `execute `shutdown /s /t 0`;
3) After Windows is up again, start `resmon.exe`, just to be sure, that ports are free;
4) Run `docker-compose up`.

**Comment by VlaD-T** [comment]
Yes. Had the following message:
![grafik](https://user-images.githubusercontent.com/14137015/58787507-39cba680-85ea-11e9-89bf-12870e6b5b4c.png)

So the containers were up, but still couldn't load the page...

**Comment by VlaD-T** [comment]
So, I've noticed that docker still starts automatically, although it's switched to "off" in settings. Here is a workaround:

1 - Open Regedit
2 - Check “HKCU\Software\Microsoft\Windows\CurrentVersion\Run” and “HKLM\Software\Microsoft\Windows\CurrentVersion\Run” (mine was under HKCU).
3 - Remove the entry with “Docker for Windows”.
4 - Restart the computer.

**Comment by naraesk** [comment]
`dokcer-compose.yml` contains `restart: always` for every service. I've found that more convenient so far. But most likely this causes your problems, so it might be better to omit this, isn't it?

**Comment by VlaD-T** [comment]
This could be also a good solution.
