### ISSUE TITLE
UI - New visualization

### ISSUE THREAD

**Issue by VlaD-T** [softvis-research/Getaviz#81]
At the moment, we can't generate a new visualization from **UI**, because we try to reach generator from client and not from server. So the possible solution is to create a `php script`, which calls the **generator**. So the logic would be like:

`UI input -> php script -> generator.`   Right?

Script is very simple:
`<? php Header("Location: http://BACKEND:8080?params(received from form)....") ?>`

My questions are:
1) Do I have to execute maven build, so that generator would be accessible? 
2) If not, what are prerequisites for generator?

**Comment by naraesk** [comment]
> So the logic would be like:
> 
> `UI input -> php script -> generator.` Right?

Correct

> My questions are:
> 
> 1. Do I have to execute maven build, so that generator would be accessible?

This should not be necessary.

> 2. If not, what are prerequisites for generator?
The generator container a.k.a. backend service needs to be running (via docker-compose). Should be all.

**Comment by VlaD-T** [comment]
Made the request with cURL and received the following result: 
![grafik](https://user-images.githubusercontent.com/14137015/58958303-e6508880-87a2-11e9-883c-20295707b5fc.png)

First line is the information about redirection. So I'm trying to follow this link (view it in a separate window), but can't reach anything.

![grafik](https://user-images.githubusercontent.com/14137015/58958554-74c50a00-87a3-11e9-8401-aa7e46b793ae.png)


Debugger shows no errors. 
![grafik](https://user-images.githubusercontent.com/14137015/58958578-84dce980-87a3-11e9-8790-3bb173f15ab8.png)

**Comment by naraesk** [comment]
> Made the request with cURL and received the following result:
> ![grafik](https://user-images.githubusercontent.com/14137015/58958303-e6508880-87a2-11e9-883c-20295707b5fc.png)

Looks good

> Which adress did I have to use? Localhost?
> 
> Tried like so: http://localhost:8082/ui/index.php?aframe=true&model=default&setup=web_a-frame/default&srcDir=data-gen

Yes, that's correct and should work when you open the url. Maybe the visualization could not be generated? Wtih `docker exec -it ID_OF_BACKEND_CONTAINER /bin/sh` you can run a shell inside the backend container (replace ID_OF_BACKEND_CONTAINER with the actual id). You will see a directory `data-gen`. Inside the directroy should be a subdirectory `default` with the model.html and metaData.json inside.

**Comment by VlaD-T** [comment]
What do I have to write here? 
![grafik](https://user-images.githubusercontent.com/14137015/58962073-b311f780-87aa-11e9-8154-8144777eb0bc.png)

p.s. tried to skip this step with enter, but it didn't work.

**Comment by naraesk** [comment]
Well, it's a shell. `ls` shows you the directory content. With `cd` you can navigate.

**Comment by VlaD-T** [comment]
Ah, sorry :D 
So... it seems like I don't have this files, that's why I'm getting this 404 error...
![grafik](https://user-images.githubusercontent.com/14137015/58962379-5400b280-87ab-11e9-92d4-cfc2bc00a815.png)

**Comment by naraesk** [comment]
Yes. Unfortunately the generator does not print a log file at the moment. Will fix this tomorrow, that will simplify generator debugging. In any case, the visualization could not be created. If I had to guess, I would say that the parameter passing of your PHP script might not work properly.

**Comment by VlaD-T** [comment]
Yes, ypu are right. Here's what docker writes:
![grafik](https://user-images.githubusercontent.com/14137015/58963017-b1e1ca00-87ac-11e9-9c7d-06878ae90f59.png)

**Comment by naraesk** [comment]
Have you entered a valid URL to a jar file into the form? If so, then your PHP script messes up something.

**Comment by VlaD-T** [comment]
Yes, looks like that. I suppose, that that's because I'm sending paramters in array. I'll try to write them in URL, like before.

**Comment by VlaD-T** [comment]
Hell yeah, it works  :D 
Had to use curl less method. Don't know why it didn't work with curl...

![grafik](https://user-images.githubusercontent.com/14137015/59085611-7277c280-88ff-11e9-875f-ebe99b419405.png)
