### ISSUE TITLE
UI - Webpack

### ISSUE THREAD

**Issue by VlaD-T** [softvis-research/Getaviz#82]
I see, that there is a webpack used for UI (in devDependencies, in package.json), but can't find where it's used (any build/serve command). 

What does it do in this project?

**Comment by naraesk** [comment]
Oh, it does nothing and can be deleted. I played around with it but webpack was not really compatible with our current architecture. Would require a lot of changes to make it work. Therefore we stayed with npm for now, even if webpack would be useful through.
