### ISSUE TITLE
Inactive backend

### ISSUE THREAD

**Issue by VlaD-T** [softvis-research/Getaviz#84]
Wanted to test generator-connector again, but there seems to be a problem now:
I'm trying to start the generator, but the backend isn't active. 

![grafik](https://user-images.githubusercontent.com/14137015/59780688-afa66200-92ba-11e9-9f08-c9f671bc4f11.png)

So I don't receive any message, that generator does anything. And each time I run docker-compose up, I see following messages:

![grafik](https://user-images.githubusercontent.com/14137015/59781332-e3ce5280-92bb-11e9-9a30-1ee3d1eabc29.png)

Any guesses?

**Comment by naraesk** [comment]
Have you already rebuild the backend container?

**Comment by VlaD-T** [comment]
Ehm.. how? :) You mean `mvn install`? It was a new clone, so all files were fresh. I did `mvn install`, than for UI `npm i` (wasn't probably needed, but anyway) and tried to start `docker-compose up`.

**Comment by naraesk** [comment]
With `docker build backend --no-cache`

Some days ago I pushed some changes to the structure of the docker image. Most likely, that's why you get this error message and rebuilding should fix this. Usually, this step is not necessary. Only in this situation, since the dockerfile itself changed.

**Comment by VlaD-T** [comment]
Should there really stay "backend" or something different, like backend-container name/ip?

![grafik](https://user-images.githubusercontent.com/14137015/59843425-d61ada80-9358-11e9-89dd-fa74431cca0b.png)

**Comment by naraesk** [comment]
`docker-compose`, not `docker`, sorry
