### ISSUE TITLE
Ruby gem issue building docker images

### ISSUE THREAD

**Issue by lfcortes12** [softvis-research/Getaviz#86]
I'm building docker images and I got this issue:

`Step 12/15 : RUN gem install bundler && bundle install --jobs 20 --retry 5 # might be better?
 ---> Running in 608cd71ddee5
Successfully installed bundler-2.0.2
1 gem installed
Fetching gem metadata from https://rubygems.org/...........
Could not find bootstrap-sass-3.2.0.2 in any of the sources
ERROR: Service 'eval' failed to build: The command '/bin/sh -c gem install bundler && bundle install --jobs 20 --retry 5 # might be better?' returned a non-zero code: 7`

**Comment by naraesk** [comment]
The master branch cannot be build at the moment due to outdated packages. Currently, we are sorting out some issues on the development branch, then we will push to master. In the mean time, please use the development branch.

**Comment by lfcortes12** [comment]
Thanks @naraesk. it works on development branch
