### ISSUE TITLE
Backend exited with code 1

### ISSUE THREAD

**Issue by VlaD-T** [softvis-research/Getaviz#87]
Did ` docker-compose build --no-cache backend`, and afterwards `docker-compose up` and received following error: 

![grafik](https://user-images.githubusercontent.com/14137015/60190034-41215100-9832-11e9-821a-616722a554d8.png)

And
![grafik](https://user-images.githubusercontent.com/14137015/60190255-a2492480-9832-11e9-9e0b-90509b00c7ce.png)

**Comment by VlaD-T** [comment]
Tried to find more information about this "exec user process caused..." problem [and here says everyone](https://forums.docker.com/t/standard-init-linux-go-175-exec-user-process-caused-no-such-file/20025/8) it's about endings..

**Comment by naraesk** [comment]
Yes, git changes the line endings automatically. But are you user you are using latest development? There this should not happen anymore.

**Comment by naraesk** [comment]
What does your Dockerfile for generator2 looks like?

**Comment by naraesk** [comment]
Your comment in #88 indicates that this is working now? @VlaD-T

**Comment by naraesk** [comment]
broken (agian) with commit a9f60bf912aa869b4503e9887f9dae0c5638f3f3
fixed with commit 208d42920164428fb093a781d5f79c20016a09d8

**Comment by naraesk** [comment]
Finally testet with Windows 10, all tests passed
