### ISSUE TITLE
Eval exited with code 127 (Windows)

### ISSUE THREAD

**Issue by VlaD-T** [softvis-research/Getaviz#88]
After a new `pull`, `docker-compose build` and `mvn install`, tried to start docker.

![grafik](https://user-images.githubusercontent.com/14137015/60255550-47fea100-98d0-11e9-86fd-92ab85ba772a.png)

**Comment by naraesk** [comment]
Looks like 127 and not 1 for me ;-)

It's the same problem as in issue #87 for backend, fun with lline endings. But you can ignore it for the moment, this does not affect frontend or backend

**Comment by naraesk** [comment]
should be fixed with commit fa78ad70e49f0ce5323f6d787f016e1cf5a8a29e

**Comment by naraesk** [comment]
For the record: problem still exists on Windosw
