### ISSUE TITLE
AFRAME is not defined

### ISSUE THREAD

**Issue by KaiHaman** [softvis-research/Getaviz#91]
AFRAME is not defined as it seems, in the entire projekt. (In my own test/mycontroller.js)
Even existing pages such as 

[index.php?setup=web_a-frame/City bank&model=City%20bank%20aframe&aframe=true
](url)

that are references by 'web_a-frame/default.js AND city bank.js" deliver the same error or are not found.
I either completely missed sometihing or A_Frame is not properly imported / used yet.

PS: Are there any working A-Frame elements in the Getaviz project on the development branch?

**Comment by naraesk** [comment]
What exactly is the error message and where is it shown? And what is not found, city bank.js?

A-Frame is imported in the index.php (starting at line 26). 

In the data directory is `City bank aframe` which contains a small aframe visualization using the city metaphor. That's the visualization that should be diplayed when going to http://localhost:8082/ui/index.php?setup=web_a-frame/City%20bank&model=City%20bank%20aframe&aframe=true

**Comment by naraesk** [comment]
Maybe your browser does not like the space in the URL (between "City" and "bank"). Try to replace it with %20

**Comment by KaiHaman** [comment]
Link is correct / page found but it as I mentioned, AFRAME is not defined:
(for your Link: http://localhost:8082/ui/index.php?setup=web_a-frame/City%20bank&model=City%20bank%20aframe&aframe=true)

GET http://localhost:8082/ui/node_modules/aframe/dist/aframe-v0.9.1.min.js net::ERR_ABORTED 404 (Not Found)
camera-beta.js:4 Uncaught ReferenceError: AFRAME is not defined
    at camera-beta.js:4
(anonymous) @ camera-beta.js:4
AframeActionController.js:95 Uncaught ReferenceError: AFRAME is not defined
    at Object.initialize (AframeActionController.js:95)
    at initializeApplication (Application.js:36)
    at Application.js:29

**Comment by naraesk** [comment]
Can you please share your `docker-compose.yml` file?

**Comment by KaiHaman** [comment]
version: "3"
services:
    # db:
    #     image: mysql:5.7
    #     environment:
    #         MYSQL_ROOT_PASSWORD: dbpassword_for_user
    #         MYSQL_DATABASE: eval_server_development
    #         MYSQL_USER: db_username
    #         MYSQL_PASSWORD: dbpassword_for_user
    #     restart: always
    # eval:
    #     build: evaluationserver
    #     restart: always
    #     env_file: evaluationserver/env
    #     command: "./bin/wait-for-it.sh db:3306 -s -t 30 -- ./bin/docker_start"
    #     #volumes:
    #     #- ./evaluationserver:/usr/src/app
    #     ports:
    #         - "8081:8081" 
    #     depends_on:
    #         - db
    frontend:
        build: ui/
        restart: always
        volumes:
            - ./ui:/var/www/html/ui # uncomment only for ui development
            - data-gen:/var/www/html/ui/data-gen
        ports:
            - "8082:80"
        networks:
            - default
        depends_on:
            - backend
    backend:
        build: generator2/org.getaviz.generator/
        restart: always
        volumes: 
            - data-gen:/var/lib/jetty/data-gen
            #- ./generator2/org.getaviz.generator/target/org.getaviz.generator-1.0.0-SNAPSHOT.war:/var/lib/jetty/webapps/root.war # uncomment only for generator development
            #- ./generator2/org.getaviz.generator/settings.properties:/opt/config/settings.properties # uncomment only for generator development
            #- ./generator2/output:/var/lib/jetty/output/ # uncomment only for generator development
            #- ./generator2/logs:/var/lib/jetty/logs # uncomment only for generator development
        ports:
            - "8083:8080"
        networks:
            - default
        depends_on:
            - neo4j
            - volumes-provisioner
    neo4j:
        image: neo4j:3.5.1
        restart: always
        ports:
            - "7474:7474"
            - "7687:7687"
        environment:
            NEO4J_AUTH: "none"
        networks:
            - default
    volumes-provisioner:
        image: hasnat/volumes-provisioner
        environment:
            PROVISION_DIRECTORIES: "100:101:0755:/var/data"
        volumes:
            - data-gen:/var/data
volumes:
  data-gen:
    
networks:
    default:
        driver: bridge

**Comment by naraesk** [comment]
Ok, so does the file `ui/node_modules/aframe/dist/aframe-v0.9.1.min.js` exist on your device? Did you execute `npm install` as described in the wiki?

**Comment by KaiHaman** [comment]
Yes I did, and just now to verify again.

**Comment by naraesk** [comment]
So the file does exist?

**Comment by KaiHaman** [comment]
ui/node_modules/aframe/dist/aframe-v0.9.2.min.js instead of ui/node_modules/aframe/dist/aframe-v0.9.1.min.js

Give me a sec. might just be the problem since index.php does not find it

**Comment by KaiHaman** [comment]
in index.php:         

$loadFramework = "<script src=\"node_modules/aframe/dist/aframe-v0.9.1.min.js\"></script>";

--> So it does not find it? A-Frame update and the link was hardcoded maybe?

**Comment by KaiHaman** [comment]
changed it everywhere from v0.9.2. This is working now: http://localhost:8082/ui/index.php?setup=web_a-frame/City%20bank&model=City%20bank%20aframe&aframe=true

Thank you very much!

**Comment by naraesk** [comment]
Well, regarding your issue: It should wrok if you change it to 0.9.2

The dependencies are defined in the `package.json`. There it says version 0.9.1 explicitly (line 9). Therefore, npm should always download 0.9.1 Although, when running `npm install` it prints the following:

> $ npm install
audited 374 packages in 1.382s
found 13 vulnerabilities (5 low, 2 moderate, 6 high)
  run `npm audit fix` to fix them, or `npm audit` for details

If you used `npm audit fix` npm will update your package.json to use Aframe 0.9.2 instead of 0.9.1, which will break index.php. You should see in your git clinet that package.json changed accordingly. Just revert your changes to the original state of the development branch and it should work again.

Anyway, most likely we should change the import to `aframe-master.min.js` instead of `aframe-v0.9.2.min.js`
