### ISSUE TITLE
Refactoring JQA2RD

### ISSUE THREAD

**Issue by naraesk** [softvis-research/Getaviz#93]
Currently, the classes JQA2RD consists of the attributes dataDisks and methodDisks which determine if we create disks or disksegments. This makes the code very complicated. To simplify, we could use the Factory pattern (https://jaxenter.de/mit-factory-pattern-designprobleme-losen-5040), so that both variables disappear and we only call rdelementfactory.createElement(...). rdelementfactory returns a disk or a disksegment depending on both variables. Testcases have to be created for the factory as well.

Some general hints:
* only the classes implementing the step interface are supposed to call the config.objects directy. All other classes/methods are called by using the required values
* only the classes implementing the step or rdelement interface are supposed to query the datbase

The factory must not know the config object or the database connector!

**Comment by Lukasz-kal** [comment]
Logic of the selection (and creating new objects) is now in a new class - RDElementsFactory.
